#import "FAKIcon.h"

@interface FAKIonIcons : FAKIcon

// Generated Code
+ (instancetype)iosAddIconWithSize:(CGFloat)size;
+ (instancetype)iosAddCircleIconWithSize:(CGFloat)size;
+ (instancetype)iosAddCircleOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosAirplaneIconWithSize:(CGFloat)size;
+ (instancetype)iosAlarmIconWithSize:(CGFloat)size;
+ (instancetype)iosAlbumsIconWithSize:(CGFloat)size;
+ (instancetype)iosAlertIconWithSize:(CGFloat)size;
+ (instancetype)iosAmericanFootballIconWithSize:(CGFloat)size;
+ (instancetype)iosAnalyticsIconWithSize:(CGFloat)size;
+ (instancetype)iosApertureIconWithSize:(CGFloat)size;
+ (instancetype)iosAppsIconWithSize:(CGFloat)size;
+ (instancetype)iosAppstoreIconWithSize:(CGFloat)size;
+ (instancetype)iosArchiveIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowBackIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowDownIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowDropdownIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowDropdownCircleIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowDropleftIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowDropleftCircleIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowDroprightIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowDroprightCircleIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowDropupIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowDropupCircleIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowForwardIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowRoundBackIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowRoundDownIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowRoundForwardIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowRoundUpIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowUpIconWithSize:(CGFloat)size;
+ (instancetype)iosAtIconWithSize:(CGFloat)size;
+ (instancetype)iosAttachIconWithSize:(CGFloat)size;
+ (instancetype)iosBackspaceIconWithSize:(CGFloat)size;
+ (instancetype)iosBarcodeIconWithSize:(CGFloat)size;
+ (instancetype)iosBaseballIconWithSize:(CGFloat)size;
+ (instancetype)iosBasketIconWithSize:(CGFloat)size;
+ (instancetype)iosBasketballIconWithSize:(CGFloat)size;
+ (instancetype)iosBatteryChargingIconWithSize:(CGFloat)size;
+ (instancetype)iosBatteryDeadIconWithSize:(CGFloat)size;
+ (instancetype)iosBatteryFullIconWithSize:(CGFloat)size;
+ (instancetype)iosBeakerIconWithSize:(CGFloat)size;
+ (instancetype)iosBedIconWithSize:(CGFloat)size;
+ (instancetype)iosBeerIconWithSize:(CGFloat)size;
+ (instancetype)iosBicycleIconWithSize:(CGFloat)size;
+ (instancetype)iosBluetoothIconWithSize:(CGFloat)size;
+ (instancetype)iosBoatIconWithSize:(CGFloat)size;
+ (instancetype)iosBodyIconWithSize:(CGFloat)size;
+ (instancetype)iosBonfireIconWithSize:(CGFloat)size;
+ (instancetype)iosBookIconWithSize:(CGFloat)size;
+ (instancetype)iosBookmarkIconWithSize:(CGFloat)size;
+ (instancetype)iosBookmarksIconWithSize:(CGFloat)size;
+ (instancetype)iosBowtieIconWithSize:(CGFloat)size;
+ (instancetype)iosBriefcaseIconWithSize:(CGFloat)size;
+ (instancetype)iosBrowsersIconWithSize:(CGFloat)size;
+ (instancetype)iosBrushIconWithSize:(CGFloat)size;
+ (instancetype)iosBugIconWithSize:(CGFloat)size;
+ (instancetype)iosBuildIconWithSize:(CGFloat)size;
+ (instancetype)iosBulbIconWithSize:(CGFloat)size;
+ (instancetype)iosBusIconWithSize:(CGFloat)size;
+ (instancetype)iosBusinessIconWithSize:(CGFloat)size;
+ (instancetype)iosCafeIconWithSize:(CGFloat)size;
+ (instancetype)iosCalculatorIconWithSize:(CGFloat)size;
+ (instancetype)iosCalendarIconWithSize:(CGFloat)size;
+ (instancetype)iosCallIconWithSize:(CGFloat)size;
+ (instancetype)iosCameraIconWithSize:(CGFloat)size;
+ (instancetype)iosCarIconWithSize:(CGFloat)size;
+ (instancetype)iosCardIconWithSize:(CGFloat)size;
+ (instancetype)iosCartIconWithSize:(CGFloat)size;
+ (instancetype)iosCashIconWithSize:(CGFloat)size;
+ (instancetype)iosCellularIconWithSize:(CGFloat)size;
+ (instancetype)iosChatboxesIconWithSize:(CGFloat)size;
+ (instancetype)iosChatbubblesIconWithSize:(CGFloat)size;
+ (instancetype)iosCheckboxIconWithSize:(CGFloat)size;
+ (instancetype)iosCheckboxOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosCheckmarkIconWithSize:(CGFloat)size;
+ (instancetype)iosCheckmarkCircleIconWithSize:(CGFloat)size;
+ (instancetype)iosCheckmarkCircleOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosClipboardIconWithSize:(CGFloat)size;
+ (instancetype)iosClockIconWithSize:(CGFloat)size;
+ (instancetype)iosCloseIconWithSize:(CGFloat)size;
+ (instancetype)iosCloseCircleIconWithSize:(CGFloat)size;
+ (instancetype)iosCloseCircleOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosCloudIconWithSize:(CGFloat)size;
+ (instancetype)iosCloudCircleIconWithSize:(CGFloat)size;
+ (instancetype)iosCloudDoneIconWithSize:(CGFloat)size;
+ (instancetype)iosCloudDownloadIconWithSize:(CGFloat)size;
+ (instancetype)iosCloudOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosCloudUploadIconWithSize:(CGFloat)size;
+ (instancetype)iosCloudyIconWithSize:(CGFloat)size;
+ (instancetype)iosCloudyNightIconWithSize:(CGFloat)size;
+ (instancetype)iosCodeIconWithSize:(CGFloat)size;
+ (instancetype)iosCodeDownloadIconWithSize:(CGFloat)size;
+ (instancetype)iosCodeWorkingIconWithSize:(CGFloat)size;
+ (instancetype)iosCogIconWithSize:(CGFloat)size;
+ (instancetype)iosColorFillIconWithSize:(CGFloat)size;
+ (instancetype)iosColorFilterIconWithSize:(CGFloat)size;
+ (instancetype)iosColorPaletteIconWithSize:(CGFloat)size;
+ (instancetype)iosColorWandIconWithSize:(CGFloat)size;
+ (instancetype)iosCompassIconWithSize:(CGFloat)size;
+ (instancetype)iosConstructIconWithSize:(CGFloat)size;
+ (instancetype)iosContactIconWithSize:(CGFloat)size;
+ (instancetype)iosContactsIconWithSize:(CGFloat)size;
+ (instancetype)iosContractIconWithSize:(CGFloat)size;
+ (instancetype)iosContrastIconWithSize:(CGFloat)size;
+ (instancetype)iosCopyIconWithSize:(CGFloat)size;
+ (instancetype)iosCreateIconWithSize:(CGFloat)size;
+ (instancetype)iosCropIconWithSize:(CGFloat)size;
+ (instancetype)iosCubeIconWithSize:(CGFloat)size;
+ (instancetype)iosCutIconWithSize:(CGFloat)size;
+ (instancetype)iosDesktopIconWithSize:(CGFloat)size;
+ (instancetype)iosDiscIconWithSize:(CGFloat)size;
+ (instancetype)iosDocumentIconWithSize:(CGFloat)size;
+ (instancetype)iosDoneAllIconWithSize:(CGFloat)size;
+ (instancetype)iosDownloadIconWithSize:(CGFloat)size;
+ (instancetype)iosEaselIconWithSize:(CGFloat)size;
+ (instancetype)iosEggIconWithSize:(CGFloat)size;
+ (instancetype)iosExitIconWithSize:(CGFloat)size;
+ (instancetype)iosExpandIconWithSize:(CGFloat)size;
+ (instancetype)iosEyeIconWithSize:(CGFloat)size;
+ (instancetype)iosEyeOffIconWithSize:(CGFloat)size;
+ (instancetype)iosFastforwardIconWithSize:(CGFloat)size;
+ (instancetype)iosFemaleIconWithSize:(CGFloat)size;
+ (instancetype)iosFilingIconWithSize:(CGFloat)size;
+ (instancetype)iosFilmIconWithSize:(CGFloat)size;
+ (instancetype)iosFingerPrintIconWithSize:(CGFloat)size;
+ (instancetype)iosFitnessIconWithSize:(CGFloat)size;
+ (instancetype)iosFlagIconWithSize:(CGFloat)size;
+ (instancetype)iosFlameIconWithSize:(CGFloat)size;
+ (instancetype)iosFlashIconWithSize:(CGFloat)size;
+ (instancetype)iosFlashOffIconWithSize:(CGFloat)size;
+ (instancetype)iosFlashlightIconWithSize:(CGFloat)size;
+ (instancetype)iosFlaskIconWithSize:(CGFloat)size;
+ (instancetype)iosFlowerIconWithSize:(CGFloat)size;
+ (instancetype)iosFolderIconWithSize:(CGFloat)size;
+ (instancetype)iosFolderOpenIconWithSize:(CGFloat)size;
+ (instancetype)iosFootballIconWithSize:(CGFloat)size;
+ (instancetype)iosFunnelIconWithSize:(CGFloat)size;
+ (instancetype)iosGiftIconWithSize:(CGFloat)size;
+ (instancetype)iosGitBranchIconWithSize:(CGFloat)size;
+ (instancetype)iosGitCommitIconWithSize:(CGFloat)size;
+ (instancetype)iosGitCompareIconWithSize:(CGFloat)size;
+ (instancetype)iosGitMergeIconWithSize:(CGFloat)size;
+ (instancetype)iosGitNetworkIconWithSize:(CGFloat)size;
+ (instancetype)iosGitPullRequestIconWithSize:(CGFloat)size;
+ (instancetype)iosGlassesIconWithSize:(CGFloat)size;
+ (instancetype)iosGlobeIconWithSize:(CGFloat)size;
+ (instancetype)iosGridIconWithSize:(CGFloat)size;
+ (instancetype)iosHammerIconWithSize:(CGFloat)size;
+ (instancetype)iosHandIconWithSize:(CGFloat)size;
+ (instancetype)iosHappyIconWithSize:(CGFloat)size;
+ (instancetype)iosHeadsetIconWithSize:(CGFloat)size;
+ (instancetype)iosHeartIconWithSize:(CGFloat)size;
+ (instancetype)iosHeartDislikeIconWithSize:(CGFloat)size;
+ (instancetype)iosHeartEmptyIconWithSize:(CGFloat)size;
+ (instancetype)iosHeartHalfIconWithSize:(CGFloat)size;
+ (instancetype)iosHelpIconWithSize:(CGFloat)size;
+ (instancetype)iosHelpBuoyIconWithSize:(CGFloat)size;
+ (instancetype)iosHelpCircleIconWithSize:(CGFloat)size;
+ (instancetype)iosHelpCircleOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosHomeIconWithSize:(CGFloat)size;
+ (instancetype)iosHourglassIconWithSize:(CGFloat)size;
+ (instancetype)iosIceCreamIconWithSize:(CGFloat)size;
+ (instancetype)iosImageIconWithSize:(CGFloat)size;
+ (instancetype)iosImagesIconWithSize:(CGFloat)size;
+ (instancetype)iosInfiniteIconWithSize:(CGFloat)size;
+ (instancetype)iosInformationIconWithSize:(CGFloat)size;
+ (instancetype)iosInformationCircleIconWithSize:(CGFloat)size;
+ (instancetype)iosInformationCircleOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosJetIconWithSize:(CGFloat)size;
+ (instancetype)iosJournalIconWithSize:(CGFloat)size;
+ (instancetype)iosKeyIconWithSize:(CGFloat)size;
+ (instancetype)iosKeypadIconWithSize:(CGFloat)size;
+ (instancetype)iosLaptopIconWithSize:(CGFloat)size;
+ (instancetype)iosLeafIconWithSize:(CGFloat)size;
+ (instancetype)iosLinkIconWithSize:(CGFloat)size;
+ (instancetype)iosListIconWithSize:(CGFloat)size;
+ (instancetype)iosListBoxIconWithSize:(CGFloat)size;
+ (instancetype)iosLocateIconWithSize:(CGFloat)size;
+ (instancetype)iosLockIconWithSize:(CGFloat)size;
+ (instancetype)iosLogInIconWithSize:(CGFloat)size;
+ (instancetype)iosLogOutIconWithSize:(CGFloat)size;
+ (instancetype)iosMagnetIconWithSize:(CGFloat)size;
+ (instancetype)iosMailIconWithSize:(CGFloat)size;
+ (instancetype)iosMailOpenIconWithSize:(CGFloat)size;
+ (instancetype)iosMailUnreadIconWithSize:(CGFloat)size;
+ (instancetype)iosMaleIconWithSize:(CGFloat)size;
+ (instancetype)iosManIconWithSize:(CGFloat)size;
+ (instancetype)iosMapIconWithSize:(CGFloat)size;
+ (instancetype)iosMedalIconWithSize:(CGFloat)size;
+ (instancetype)iosMedicalIconWithSize:(CGFloat)size;
+ (instancetype)iosMedkitIconWithSize:(CGFloat)size;
+ (instancetype)iosMegaphoneIconWithSize:(CGFloat)size;
+ (instancetype)iosMenuIconWithSize:(CGFloat)size;
+ (instancetype)iosMicIconWithSize:(CGFloat)size;
+ (instancetype)iosMicOffIconWithSize:(CGFloat)size;
+ (instancetype)iosMicrophoneIconWithSize:(CGFloat)size;
+ (instancetype)iosMoonIconWithSize:(CGFloat)size;
+ (instancetype)iosMoreIconWithSize:(CGFloat)size;
+ (instancetype)iosMoveIconWithSize:(CGFloat)size;
+ (instancetype)iosMusicalNoteIconWithSize:(CGFloat)size;
+ (instancetype)iosMusicalNotesIconWithSize:(CGFloat)size;
+ (instancetype)iosNavigateIconWithSize:(CGFloat)size;
+ (instancetype)iosNotificationsIconWithSize:(CGFloat)size;
+ (instancetype)iosNotificationsOffIconWithSize:(CGFloat)size;
+ (instancetype)iosNotificationsOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosNuclearIconWithSize:(CGFloat)size;
+ (instancetype)iosNutritionIconWithSize:(CGFloat)size;
+ (instancetype)iosOpenIconWithSize:(CGFloat)size;
+ (instancetype)iosOptionsIconWithSize:(CGFloat)size;
+ (instancetype)iosOutletIconWithSize:(CGFloat)size;
+ (instancetype)iosPaperIconWithSize:(CGFloat)size;
+ (instancetype)iosPaperPlaneIconWithSize:(CGFloat)size;
+ (instancetype)iosPartlySunnyIconWithSize:(CGFloat)size;
+ (instancetype)iosPauseIconWithSize:(CGFloat)size;
+ (instancetype)iosPawIconWithSize:(CGFloat)size;
+ (instancetype)iosPeopleIconWithSize:(CGFloat)size;
+ (instancetype)iosPersonIconWithSize:(CGFloat)size;
+ (instancetype)iosPersonAddIconWithSize:(CGFloat)size;
+ (instancetype)iosPhoneLandscapeIconWithSize:(CGFloat)size;
+ (instancetype)iosPhonePortraitIconWithSize:(CGFloat)size;
+ (instancetype)iosPhotosIconWithSize:(CGFloat)size;
+ (instancetype)iosPieIconWithSize:(CGFloat)size;
+ (instancetype)iosPinIconWithSize:(CGFloat)size;
+ (instancetype)iosPintIconWithSize:(CGFloat)size;
+ (instancetype)iosPizzaIconWithSize:(CGFloat)size;
+ (instancetype)iosPlanetIconWithSize:(CGFloat)size;
+ (instancetype)iosPlayIconWithSize:(CGFloat)size;
+ (instancetype)iosPlayCircleIconWithSize:(CGFloat)size;
+ (instancetype)iosPodiumIconWithSize:(CGFloat)size;
+ (instancetype)iosPowerIconWithSize:(CGFloat)size;
+ (instancetype)iosPricetagIconWithSize:(CGFloat)size;
+ (instancetype)iosPricetagsIconWithSize:(CGFloat)size;
+ (instancetype)iosPrintIconWithSize:(CGFloat)size;
+ (instancetype)iosPulseIconWithSize:(CGFloat)size;
+ (instancetype)iosQrScannerIconWithSize:(CGFloat)size;
+ (instancetype)iosQuoteIconWithSize:(CGFloat)size;
+ (instancetype)iosRadioIconWithSize:(CGFloat)size;
+ (instancetype)iosRadioButtonOffIconWithSize:(CGFloat)size;
+ (instancetype)iosRadioButtonOnIconWithSize:(CGFloat)size;
+ (instancetype)iosRainyIconWithSize:(CGFloat)size;
+ (instancetype)iosRecordingIconWithSize:(CGFloat)size;
+ (instancetype)iosRedoIconWithSize:(CGFloat)size;
+ (instancetype)iosRefreshIconWithSize:(CGFloat)size;
+ (instancetype)iosRefreshCircleIconWithSize:(CGFloat)size;
+ (instancetype)iosRemoveIconWithSize:(CGFloat)size;
+ (instancetype)iosRemoveCircleIconWithSize:(CGFloat)size;
+ (instancetype)iosRemoveCircleOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosReorderIconWithSize:(CGFloat)size;
+ (instancetype)iosRepeatIconWithSize:(CGFloat)size;
+ (instancetype)iosResizeIconWithSize:(CGFloat)size;
+ (instancetype)iosRestaurantIconWithSize:(CGFloat)size;
+ (instancetype)iosReturnLeftIconWithSize:(CGFloat)size;
+ (instancetype)iosReturnRightIconWithSize:(CGFloat)size;
+ (instancetype)iosReverseCameraIconWithSize:(CGFloat)size;
+ (instancetype)iosRewindIconWithSize:(CGFloat)size;
+ (instancetype)iosRibbonIconWithSize:(CGFloat)size;
+ (instancetype)iosRocketIconWithSize:(CGFloat)size;
+ (instancetype)iosRoseIconWithSize:(CGFloat)size;
+ (instancetype)iosSadIconWithSize:(CGFloat)size;
+ (instancetype)iosSaveIconWithSize:(CGFloat)size;
+ (instancetype)iosSchoolIconWithSize:(CGFloat)size;
+ (instancetype)iosSearchIconWithSize:(CGFloat)size;
+ (instancetype)iosSendIconWithSize:(CGFloat)size;
+ (instancetype)iosSettingsIconWithSize:(CGFloat)size;
+ (instancetype)iosShareIconWithSize:(CGFloat)size;
+ (instancetype)iosShareAltIconWithSize:(CGFloat)size;
+ (instancetype)iosShirtIconWithSize:(CGFloat)size;
+ (instancetype)iosShuffleIconWithSize:(CGFloat)size;
+ (instancetype)iosSkipBackwardIconWithSize:(CGFloat)size;
+ (instancetype)iosSkipForwardIconWithSize:(CGFloat)size;
+ (instancetype)iosSnowIconWithSize:(CGFloat)size;
+ (instancetype)iosSpeedometerIconWithSize:(CGFloat)size;
+ (instancetype)iosSquareIconWithSize:(CGFloat)size;
+ (instancetype)iosSquareOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosStarIconWithSize:(CGFloat)size;
+ (instancetype)iosStarHalfIconWithSize:(CGFloat)size;
+ (instancetype)iosStarOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosStatsIconWithSize:(CGFloat)size;
+ (instancetype)iosStopwatchIconWithSize:(CGFloat)size;
+ (instancetype)iosSubwayIconWithSize:(CGFloat)size;
+ (instancetype)iosSunnyIconWithSize:(CGFloat)size;
+ (instancetype)iosSwapIconWithSize:(CGFloat)size;
+ (instancetype)iosSwitchIconWithSize:(CGFloat)size;
+ (instancetype)iosSyncIconWithSize:(CGFloat)size;
+ (instancetype)iosTabletLandscapeIconWithSize:(CGFloat)size;
+ (instancetype)iosTabletPortraitIconWithSize:(CGFloat)size;
+ (instancetype)iosTennisballIconWithSize:(CGFloat)size;
+ (instancetype)iosTextIconWithSize:(CGFloat)size;
+ (instancetype)iosThermometerIconWithSize:(CGFloat)size;
+ (instancetype)iosThumbsDownIconWithSize:(CGFloat)size;
+ (instancetype)iosThumbsUpIconWithSize:(CGFloat)size;
+ (instancetype)iosThunderstormIconWithSize:(CGFloat)size;
+ (instancetype)iosTimeIconWithSize:(CGFloat)size;
+ (instancetype)iosTimerIconWithSize:(CGFloat)size;
+ (instancetype)iosTodayIconWithSize:(CGFloat)size;
+ (instancetype)iosTrainIconWithSize:(CGFloat)size;
+ (instancetype)iosTransgenderIconWithSize:(CGFloat)size;
+ (instancetype)iosTrashIconWithSize:(CGFloat)size;
+ (instancetype)iosTrendingDownIconWithSize:(CGFloat)size;
+ (instancetype)iosTrendingUpIconWithSize:(CGFloat)size;
+ (instancetype)iosTrophyIconWithSize:(CGFloat)size;
+ (instancetype)iosTvIconWithSize:(CGFloat)size;
+ (instancetype)iosUmbrellaIconWithSize:(CGFloat)size;
+ (instancetype)iosUndoIconWithSize:(CGFloat)size;
+ (instancetype)iosUnlockIconWithSize:(CGFloat)size;
+ (instancetype)iosVideocamIconWithSize:(CGFloat)size;
+ (instancetype)iosVolumeHighIconWithSize:(CGFloat)size;
+ (instancetype)iosVolumeLowIconWithSize:(CGFloat)size;
+ (instancetype)iosVolumeMuteIconWithSize:(CGFloat)size;
+ (instancetype)iosVolumeOffIconWithSize:(CGFloat)size;
+ (instancetype)iosWalkIconWithSize:(CGFloat)size;
+ (instancetype)iosWalletIconWithSize:(CGFloat)size;
+ (instancetype)iosWarningIconWithSize:(CGFloat)size;
+ (instancetype)iosWatchIconWithSize:(CGFloat)size;
+ (instancetype)iosWaterIconWithSize:(CGFloat)size;
+ (instancetype)iosWifiIconWithSize:(CGFloat)size;
+ (instancetype)iosWineIconWithSize:(CGFloat)size;
+ (instancetype)iosWomanIconWithSize:(CGFloat)size;
+ (instancetype)logoAndroidIconWithSize:(CGFloat)size;
+ (instancetype)logoAngularIconWithSize:(CGFloat)size;
+ (instancetype)logoAppleIconWithSize:(CGFloat)size;
+ (instancetype)logoBitbucketIconWithSize:(CGFloat)size;
+ (instancetype)logoBitcoinIconWithSize:(CGFloat)size;
+ (instancetype)logoBufferIconWithSize:(CGFloat)size;
+ (instancetype)logoChromeIconWithSize:(CGFloat)size;
+ (instancetype)logoClosedCaptioningIconWithSize:(CGFloat)size;
+ (instancetype)logoCodepenIconWithSize:(CGFloat)size;
+ (instancetype)logoCss3IconWithSize:(CGFloat)size;
+ (instancetype)logoDesignernewsIconWithSize:(CGFloat)size;
+ (instancetype)logoDribbbleIconWithSize:(CGFloat)size;
+ (instancetype)logoDropboxIconWithSize:(CGFloat)size;
+ (instancetype)logoEuroIconWithSize:(CGFloat)size;
+ (instancetype)logoFacebookIconWithSize:(CGFloat)size;
+ (instancetype)logoFlickrIconWithSize:(CGFloat)size;
+ (instancetype)logoFoursquareIconWithSize:(CGFloat)size;
+ (instancetype)logoFreebsdDevilIconWithSize:(CGFloat)size;
+ (instancetype)logoGameControllerAIconWithSize:(CGFloat)size;
+ (instancetype)logoGameControllerBIconWithSize:(CGFloat)size;
+ (instancetype)logoGithubIconWithSize:(CGFloat)size;
+ (instancetype)logoGoogleIconWithSize:(CGFloat)size;
+ (instancetype)logoGoogleplusIconWithSize:(CGFloat)size;
+ (instancetype)logoHackernewsIconWithSize:(CGFloat)size;
+ (instancetype)logoHtml5IconWithSize:(CGFloat)size;
+ (instancetype)logoInstagramIconWithSize:(CGFloat)size;
+ (instancetype)logoIonicIconWithSize:(CGFloat)size;
+ (instancetype)logoIonitronIconWithSize:(CGFloat)size;
+ (instancetype)logoJavascriptIconWithSize:(CGFloat)size;
+ (instancetype)logoLinkedinIconWithSize:(CGFloat)size;
+ (instancetype)logoMarkdownIconWithSize:(CGFloat)size;
+ (instancetype)logoModelSIconWithSize:(CGFloat)size;
+ (instancetype)logoNoSmokingIconWithSize:(CGFloat)size;
+ (instancetype)logoNodejsIconWithSize:(CGFloat)size;
+ (instancetype)logoNpmIconWithSize:(CGFloat)size;
+ (instancetype)logoOctocatIconWithSize:(CGFloat)size;
+ (instancetype)logoPinterestIconWithSize:(CGFloat)size;
+ (instancetype)logoPlaystationIconWithSize:(CGFloat)size;
+ (instancetype)logoPolymerIconWithSize:(CGFloat)size;
+ (instancetype)logoPythonIconWithSize:(CGFloat)size;
+ (instancetype)logoRedditIconWithSize:(CGFloat)size;
+ (instancetype)logoRssIconWithSize:(CGFloat)size;
+ (instancetype)logoSassIconWithSize:(CGFloat)size;
+ (instancetype)logoSkypeIconWithSize:(CGFloat)size;
+ (instancetype)logoSlackIconWithSize:(CGFloat)size;
+ (instancetype)logoSnapchatIconWithSize:(CGFloat)size;
+ (instancetype)logoSteamIconWithSize:(CGFloat)size;
+ (instancetype)logoTumblrIconWithSize:(CGFloat)size;
+ (instancetype)logoTuxIconWithSize:(CGFloat)size;
+ (instancetype)logoTwitchIconWithSize:(CGFloat)size;
+ (instancetype)logoTwitterIconWithSize:(CGFloat)size;
+ (instancetype)logoUsdIconWithSize:(CGFloat)size;
+ (instancetype)logoVimeoIconWithSize:(CGFloat)size;
+ (instancetype)logoVkIconWithSize:(CGFloat)size;
+ (instancetype)logoWhatsappIconWithSize:(CGFloat)size;
+ (instancetype)logoWindowsIconWithSize:(CGFloat)size;
+ (instancetype)logoWordpressIconWithSize:(CGFloat)size;
+ (instancetype)logoXboxIconWithSize:(CGFloat)size;
+ (instancetype)logoXingIconWithSize:(CGFloat)size;
+ (instancetype)logoYahooIconWithSize:(CGFloat)size;
+ (instancetype)logoYenIconWithSize:(CGFloat)size;
+ (instancetype)logoYoutubeIconWithSize:(CGFloat)size;
+ (instancetype)mdAddIconWithSize:(CGFloat)size;
+ (instancetype)mdAddCircleIconWithSize:(CGFloat)size;
+ (instancetype)mdAddCircleOutlineIconWithSize:(CGFloat)size;
+ (instancetype)mdAirplaneIconWithSize:(CGFloat)size;
+ (instancetype)mdAlarmIconWithSize:(CGFloat)size;
+ (instancetype)mdAlbumsIconWithSize:(CGFloat)size;
+ (instancetype)mdAlertIconWithSize:(CGFloat)size;
+ (instancetype)mdAmericanFootballIconWithSize:(CGFloat)size;
+ (instancetype)mdAnalyticsIconWithSize:(CGFloat)size;
+ (instancetype)mdApertureIconWithSize:(CGFloat)size;
+ (instancetype)mdAppsIconWithSize:(CGFloat)size;
+ (instancetype)mdAppstoreIconWithSize:(CGFloat)size;
+ (instancetype)mdArchiveIconWithSize:(CGFloat)size;
+ (instancetype)mdArrowBackIconWithSize:(CGFloat)size;
+ (instancetype)mdArrowDownIconWithSize:(CGFloat)size;
+ (instancetype)mdArrowDropdownIconWithSize:(CGFloat)size;
+ (instancetype)mdArrowDropdownCircleIconWithSize:(CGFloat)size;
+ (instancetype)mdArrowDropleftIconWithSize:(CGFloat)size;
+ (instancetype)mdArrowDropleftCircleIconWithSize:(CGFloat)size;
+ (instancetype)mdArrowDroprightIconWithSize:(CGFloat)size;
+ (instancetype)mdArrowDroprightCircleIconWithSize:(CGFloat)size;
+ (instancetype)mdArrowDropupIconWithSize:(CGFloat)size;
+ (instancetype)mdArrowDropupCircleIconWithSize:(CGFloat)size;
+ (instancetype)mdArrowForwardIconWithSize:(CGFloat)size;
+ (instancetype)mdArrowRoundBackIconWithSize:(CGFloat)size;
+ (instancetype)mdArrowRoundDownIconWithSize:(CGFloat)size;
+ (instancetype)mdArrowRoundForwardIconWithSize:(CGFloat)size;
+ (instancetype)mdArrowRoundUpIconWithSize:(CGFloat)size;
+ (instancetype)mdArrowUpIconWithSize:(CGFloat)size;
+ (instancetype)mdAtIconWithSize:(CGFloat)size;
+ (instancetype)mdAttachIconWithSize:(CGFloat)size;
+ (instancetype)mdBackspaceIconWithSize:(CGFloat)size;
+ (instancetype)mdBarcodeIconWithSize:(CGFloat)size;
+ (instancetype)mdBaseballIconWithSize:(CGFloat)size;
+ (instancetype)mdBasketIconWithSize:(CGFloat)size;
+ (instancetype)mdBasketballIconWithSize:(CGFloat)size;
+ (instancetype)mdBatteryChargingIconWithSize:(CGFloat)size;
+ (instancetype)mdBatteryDeadIconWithSize:(CGFloat)size;
+ (instancetype)mdBatteryFullIconWithSize:(CGFloat)size;
+ (instancetype)mdBeakerIconWithSize:(CGFloat)size;
+ (instancetype)mdBedIconWithSize:(CGFloat)size;
+ (instancetype)mdBeerIconWithSize:(CGFloat)size;
+ (instancetype)mdBicycleIconWithSize:(CGFloat)size;
+ (instancetype)mdBluetoothIconWithSize:(CGFloat)size;
+ (instancetype)mdBoatIconWithSize:(CGFloat)size;
+ (instancetype)mdBodyIconWithSize:(CGFloat)size;
+ (instancetype)mdBonfireIconWithSize:(CGFloat)size;
+ (instancetype)mdBookIconWithSize:(CGFloat)size;
+ (instancetype)mdBookmarkIconWithSize:(CGFloat)size;
+ (instancetype)mdBookmarksIconWithSize:(CGFloat)size;
+ (instancetype)mdBowtieIconWithSize:(CGFloat)size;
+ (instancetype)mdBriefcaseIconWithSize:(CGFloat)size;
+ (instancetype)mdBrowsersIconWithSize:(CGFloat)size;
+ (instancetype)mdBrushIconWithSize:(CGFloat)size;
+ (instancetype)mdBugIconWithSize:(CGFloat)size;
+ (instancetype)mdBuildIconWithSize:(CGFloat)size;
+ (instancetype)mdBulbIconWithSize:(CGFloat)size;
+ (instancetype)mdBusIconWithSize:(CGFloat)size;
+ (instancetype)mdBusinessIconWithSize:(CGFloat)size;
+ (instancetype)mdCafeIconWithSize:(CGFloat)size;
+ (instancetype)mdCalculatorIconWithSize:(CGFloat)size;
+ (instancetype)mdCalendarIconWithSize:(CGFloat)size;
+ (instancetype)mdCallIconWithSize:(CGFloat)size;
+ (instancetype)mdCameraIconWithSize:(CGFloat)size;
+ (instancetype)mdCarIconWithSize:(CGFloat)size;
+ (instancetype)mdCardIconWithSize:(CGFloat)size;
+ (instancetype)mdCartIconWithSize:(CGFloat)size;
+ (instancetype)mdCashIconWithSize:(CGFloat)size;
+ (instancetype)mdCellularIconWithSize:(CGFloat)size;
+ (instancetype)mdChatboxesIconWithSize:(CGFloat)size;
+ (instancetype)mdChatbubblesIconWithSize:(CGFloat)size;
+ (instancetype)mdCheckboxIconWithSize:(CGFloat)size;
+ (instancetype)mdCheckboxOutlineIconWithSize:(CGFloat)size;
+ (instancetype)mdCheckmarkIconWithSize:(CGFloat)size;
+ (instancetype)mdCheckmarkCircleIconWithSize:(CGFloat)size;
+ (instancetype)mdCheckmarkCircleOutlineIconWithSize:(CGFloat)size;
+ (instancetype)mdClipboardIconWithSize:(CGFloat)size;
+ (instancetype)mdClockIconWithSize:(CGFloat)size;
+ (instancetype)mdCloseIconWithSize:(CGFloat)size;
+ (instancetype)mdCloseCircleIconWithSize:(CGFloat)size;
+ (instancetype)mdCloseCircleOutlineIconWithSize:(CGFloat)size;
+ (instancetype)mdCloudIconWithSize:(CGFloat)size;
+ (instancetype)mdCloudCircleIconWithSize:(CGFloat)size;
+ (instancetype)mdCloudDoneIconWithSize:(CGFloat)size;
+ (instancetype)mdCloudDownloadIconWithSize:(CGFloat)size;
+ (instancetype)mdCloudOutlineIconWithSize:(CGFloat)size;
+ (instancetype)mdCloudUploadIconWithSize:(CGFloat)size;
+ (instancetype)mdCloudyIconWithSize:(CGFloat)size;
+ (instancetype)mdCloudyNightIconWithSize:(CGFloat)size;
+ (instancetype)mdCodeIconWithSize:(CGFloat)size;
+ (instancetype)mdCodeDownloadIconWithSize:(CGFloat)size;
+ (instancetype)mdCodeWorkingIconWithSize:(CGFloat)size;
+ (instancetype)mdCogIconWithSize:(CGFloat)size;
+ (instancetype)mdColorFillIconWithSize:(CGFloat)size;
+ (instancetype)mdColorFilterIconWithSize:(CGFloat)size;
+ (instancetype)mdColorPaletteIconWithSize:(CGFloat)size;
+ (instancetype)mdColorWandIconWithSize:(CGFloat)size;
+ (instancetype)mdCompassIconWithSize:(CGFloat)size;
+ (instancetype)mdConstructIconWithSize:(CGFloat)size;
+ (instancetype)mdContactIconWithSize:(CGFloat)size;
+ (instancetype)mdContactsIconWithSize:(CGFloat)size;
+ (instancetype)mdContractIconWithSize:(CGFloat)size;
+ (instancetype)mdContrastIconWithSize:(CGFloat)size;
+ (instancetype)mdCopyIconWithSize:(CGFloat)size;
+ (instancetype)mdCreateIconWithSize:(CGFloat)size;
+ (instancetype)mdCropIconWithSize:(CGFloat)size;
+ (instancetype)mdCubeIconWithSize:(CGFloat)size;
+ (instancetype)mdCutIconWithSize:(CGFloat)size;
+ (instancetype)mdDesktopIconWithSize:(CGFloat)size;
+ (instancetype)mdDiscIconWithSize:(CGFloat)size;
+ (instancetype)mdDocumentIconWithSize:(CGFloat)size;
+ (instancetype)mdDoneAllIconWithSize:(CGFloat)size;
+ (instancetype)mdDownloadIconWithSize:(CGFloat)size;
+ (instancetype)mdEaselIconWithSize:(CGFloat)size;
+ (instancetype)mdEggIconWithSize:(CGFloat)size;
+ (instancetype)mdExitIconWithSize:(CGFloat)size;
+ (instancetype)mdExpandIconWithSize:(CGFloat)size;
+ (instancetype)mdEyeIconWithSize:(CGFloat)size;
+ (instancetype)mdEyeOffIconWithSize:(CGFloat)size;
+ (instancetype)mdFastforwardIconWithSize:(CGFloat)size;
+ (instancetype)mdFemaleIconWithSize:(CGFloat)size;
+ (instancetype)mdFilingIconWithSize:(CGFloat)size;
+ (instancetype)mdFilmIconWithSize:(CGFloat)size;
+ (instancetype)mdFingerPrintIconWithSize:(CGFloat)size;
+ (instancetype)mdFitnessIconWithSize:(CGFloat)size;
+ (instancetype)mdFlagIconWithSize:(CGFloat)size;
+ (instancetype)mdFlameIconWithSize:(CGFloat)size;
+ (instancetype)mdFlashIconWithSize:(CGFloat)size;
+ (instancetype)mdFlashOffIconWithSize:(CGFloat)size;
+ (instancetype)mdFlashlightIconWithSize:(CGFloat)size;
+ (instancetype)mdFlaskIconWithSize:(CGFloat)size;
+ (instancetype)mdFlowerIconWithSize:(CGFloat)size;
+ (instancetype)mdFolderIconWithSize:(CGFloat)size;
+ (instancetype)mdFolderOpenIconWithSize:(CGFloat)size;
+ (instancetype)mdFootballIconWithSize:(CGFloat)size;
+ (instancetype)mdFunnelIconWithSize:(CGFloat)size;
+ (instancetype)mdGiftIconWithSize:(CGFloat)size;
+ (instancetype)mdGitBranchIconWithSize:(CGFloat)size;
+ (instancetype)mdGitCommitIconWithSize:(CGFloat)size;
+ (instancetype)mdGitCompareIconWithSize:(CGFloat)size;
+ (instancetype)mdGitMergeIconWithSize:(CGFloat)size;
+ (instancetype)mdGitNetworkIconWithSize:(CGFloat)size;
+ (instancetype)mdGitPullRequestIconWithSize:(CGFloat)size;
+ (instancetype)mdGlassesIconWithSize:(CGFloat)size;
+ (instancetype)mdGlobeIconWithSize:(CGFloat)size;
+ (instancetype)mdGridIconWithSize:(CGFloat)size;
+ (instancetype)mdHammerIconWithSize:(CGFloat)size;
+ (instancetype)mdHandIconWithSize:(CGFloat)size;
+ (instancetype)mdHappyIconWithSize:(CGFloat)size;
+ (instancetype)mdHeadsetIconWithSize:(CGFloat)size;
+ (instancetype)mdHeartIconWithSize:(CGFloat)size;
+ (instancetype)mdHeartDislikeIconWithSize:(CGFloat)size;
+ (instancetype)mdHeartEmptyIconWithSize:(CGFloat)size;
+ (instancetype)mdHeartHalfIconWithSize:(CGFloat)size;
+ (instancetype)mdHelpIconWithSize:(CGFloat)size;
+ (instancetype)mdHelpBuoyIconWithSize:(CGFloat)size;
+ (instancetype)mdHelpCircleIconWithSize:(CGFloat)size;
+ (instancetype)mdHelpCircleOutlineIconWithSize:(CGFloat)size;
+ (instancetype)mdHomeIconWithSize:(CGFloat)size;
+ (instancetype)mdHourglassIconWithSize:(CGFloat)size;
+ (instancetype)mdIceCreamIconWithSize:(CGFloat)size;
+ (instancetype)mdImageIconWithSize:(CGFloat)size;
+ (instancetype)mdImagesIconWithSize:(CGFloat)size;
+ (instancetype)mdInfiniteIconWithSize:(CGFloat)size;
+ (instancetype)mdInformationIconWithSize:(CGFloat)size;
+ (instancetype)mdInformationCircleIconWithSize:(CGFloat)size;
+ (instancetype)mdInformationCircleOutlineIconWithSize:(CGFloat)size;
+ (instancetype)mdJetIconWithSize:(CGFloat)size;
+ (instancetype)mdJournalIconWithSize:(CGFloat)size;
+ (instancetype)mdKeyIconWithSize:(CGFloat)size;
+ (instancetype)mdKeypadIconWithSize:(CGFloat)size;
+ (instancetype)mdLaptopIconWithSize:(CGFloat)size;
+ (instancetype)mdLeafIconWithSize:(CGFloat)size;
+ (instancetype)mdLinkIconWithSize:(CGFloat)size;
+ (instancetype)mdListIconWithSize:(CGFloat)size;
+ (instancetype)mdListBoxIconWithSize:(CGFloat)size;
+ (instancetype)mdLocateIconWithSize:(CGFloat)size;
+ (instancetype)mdLockIconWithSize:(CGFloat)size;
+ (instancetype)mdLogInIconWithSize:(CGFloat)size;
+ (instancetype)mdLogOutIconWithSize:(CGFloat)size;
+ (instancetype)mdMagnetIconWithSize:(CGFloat)size;
+ (instancetype)mdMailIconWithSize:(CGFloat)size;
+ (instancetype)mdMailOpenIconWithSize:(CGFloat)size;
+ (instancetype)mdMailUnreadIconWithSize:(CGFloat)size;
+ (instancetype)mdMaleIconWithSize:(CGFloat)size;
+ (instancetype)mdManIconWithSize:(CGFloat)size;
+ (instancetype)mdMapIconWithSize:(CGFloat)size;
+ (instancetype)mdMedalIconWithSize:(CGFloat)size;
+ (instancetype)mdMedicalIconWithSize:(CGFloat)size;
+ (instancetype)mdMedkitIconWithSize:(CGFloat)size;
+ (instancetype)mdMegaphoneIconWithSize:(CGFloat)size;
+ (instancetype)mdMenuIconWithSize:(CGFloat)size;
+ (instancetype)mdMicIconWithSize:(CGFloat)size;
+ (instancetype)mdMicOffIconWithSize:(CGFloat)size;
+ (instancetype)mdMicrophoneIconWithSize:(CGFloat)size;
+ (instancetype)mdMoonIconWithSize:(CGFloat)size;
+ (instancetype)mdMoreIconWithSize:(CGFloat)size;
+ (instancetype)mdMoveIconWithSize:(CGFloat)size;
+ (instancetype)mdMusicalNoteIconWithSize:(CGFloat)size;
+ (instancetype)mdMusicalNotesIconWithSize:(CGFloat)size;
+ (instancetype)mdNavigateIconWithSize:(CGFloat)size;
+ (instancetype)mdNotificationsIconWithSize:(CGFloat)size;
+ (instancetype)mdNotificationsOffIconWithSize:(CGFloat)size;
+ (instancetype)mdNotificationsOutlineIconWithSize:(CGFloat)size;
+ (instancetype)mdNuclearIconWithSize:(CGFloat)size;
+ (instancetype)mdNutritionIconWithSize:(CGFloat)size;
+ (instancetype)mdOpenIconWithSize:(CGFloat)size;
+ (instancetype)mdOptionsIconWithSize:(CGFloat)size;
+ (instancetype)mdOutletIconWithSize:(CGFloat)size;
+ (instancetype)mdPaperIconWithSize:(CGFloat)size;
+ (instancetype)mdPaperPlaneIconWithSize:(CGFloat)size;
+ (instancetype)mdPartlySunnyIconWithSize:(CGFloat)size;
+ (instancetype)mdPauseIconWithSize:(CGFloat)size;
+ (instancetype)mdPawIconWithSize:(CGFloat)size;
+ (instancetype)mdPeopleIconWithSize:(CGFloat)size;
+ (instancetype)mdPersonIconWithSize:(CGFloat)size;
+ (instancetype)mdPersonAddIconWithSize:(CGFloat)size;
+ (instancetype)mdPhoneLandscapeIconWithSize:(CGFloat)size;
+ (instancetype)mdPhonePortraitIconWithSize:(CGFloat)size;
+ (instancetype)mdPhotosIconWithSize:(CGFloat)size;
+ (instancetype)mdPieIconWithSize:(CGFloat)size;
+ (instancetype)mdPinIconWithSize:(CGFloat)size;
+ (instancetype)mdPintIconWithSize:(CGFloat)size;
+ (instancetype)mdPizzaIconWithSize:(CGFloat)size;
+ (instancetype)mdPlanetIconWithSize:(CGFloat)size;
+ (instancetype)mdPlayIconWithSize:(CGFloat)size;
+ (instancetype)mdPlayCircleIconWithSize:(CGFloat)size;
+ (instancetype)mdPodiumIconWithSize:(CGFloat)size;
+ (instancetype)mdPowerIconWithSize:(CGFloat)size;
+ (instancetype)mdPricetagIconWithSize:(CGFloat)size;
+ (instancetype)mdPricetagsIconWithSize:(CGFloat)size;
+ (instancetype)mdPrintIconWithSize:(CGFloat)size;
+ (instancetype)mdPulseIconWithSize:(CGFloat)size;
+ (instancetype)mdQrScannerIconWithSize:(CGFloat)size;
+ (instancetype)mdQuoteIconWithSize:(CGFloat)size;
+ (instancetype)mdRadioIconWithSize:(CGFloat)size;
+ (instancetype)mdRadioButtonOffIconWithSize:(CGFloat)size;
+ (instancetype)mdRadioButtonOnIconWithSize:(CGFloat)size;
+ (instancetype)mdRainyIconWithSize:(CGFloat)size;
+ (instancetype)mdRecordingIconWithSize:(CGFloat)size;
+ (instancetype)mdRedoIconWithSize:(CGFloat)size;
+ (instancetype)mdRefreshIconWithSize:(CGFloat)size;
+ (instancetype)mdRefreshCircleIconWithSize:(CGFloat)size;
+ (instancetype)mdRemoveIconWithSize:(CGFloat)size;
+ (instancetype)mdRemoveCircleIconWithSize:(CGFloat)size;
+ (instancetype)mdRemoveCircleOutlineIconWithSize:(CGFloat)size;
+ (instancetype)mdReorderIconWithSize:(CGFloat)size;
+ (instancetype)mdRepeatIconWithSize:(CGFloat)size;
+ (instancetype)mdResizeIconWithSize:(CGFloat)size;
+ (instancetype)mdRestaurantIconWithSize:(CGFloat)size;
+ (instancetype)mdReturnLeftIconWithSize:(CGFloat)size;
+ (instancetype)mdReturnRightIconWithSize:(CGFloat)size;
+ (instancetype)mdReverseCameraIconWithSize:(CGFloat)size;
+ (instancetype)mdRewindIconWithSize:(CGFloat)size;
+ (instancetype)mdRibbonIconWithSize:(CGFloat)size;
+ (instancetype)mdRocketIconWithSize:(CGFloat)size;
+ (instancetype)mdRoseIconWithSize:(CGFloat)size;
+ (instancetype)mdSadIconWithSize:(CGFloat)size;
+ (instancetype)mdSaveIconWithSize:(CGFloat)size;
+ (instancetype)mdSchoolIconWithSize:(CGFloat)size;
+ (instancetype)mdSearchIconWithSize:(CGFloat)size;
+ (instancetype)mdSendIconWithSize:(CGFloat)size;
+ (instancetype)mdSettingsIconWithSize:(CGFloat)size;
+ (instancetype)mdShareIconWithSize:(CGFloat)size;
+ (instancetype)mdShareAltIconWithSize:(CGFloat)size;
+ (instancetype)mdShirtIconWithSize:(CGFloat)size;
+ (instancetype)mdShuffleIconWithSize:(CGFloat)size;
+ (instancetype)mdSkipBackwardIconWithSize:(CGFloat)size;
+ (instancetype)mdSkipForwardIconWithSize:(CGFloat)size;
+ (instancetype)mdSnowIconWithSize:(CGFloat)size;
+ (instancetype)mdSpeedometerIconWithSize:(CGFloat)size;
+ (instancetype)mdSquareIconWithSize:(CGFloat)size;
+ (instancetype)mdSquareOutlineIconWithSize:(CGFloat)size;
+ (instancetype)mdStarIconWithSize:(CGFloat)size;
+ (instancetype)mdStarHalfIconWithSize:(CGFloat)size;
+ (instancetype)mdStarOutlineIconWithSize:(CGFloat)size;
+ (instancetype)mdStatsIconWithSize:(CGFloat)size;
+ (instancetype)mdStopwatchIconWithSize:(CGFloat)size;
+ (instancetype)mdSubwayIconWithSize:(CGFloat)size;
+ (instancetype)mdSunnyIconWithSize:(CGFloat)size;
+ (instancetype)mdSwapIconWithSize:(CGFloat)size;
+ (instancetype)mdSwitchIconWithSize:(CGFloat)size;
+ (instancetype)mdSyncIconWithSize:(CGFloat)size;
+ (instancetype)mdTabletLandscapeIconWithSize:(CGFloat)size;
+ (instancetype)mdTabletPortraitIconWithSize:(CGFloat)size;
+ (instancetype)mdTennisballIconWithSize:(CGFloat)size;
+ (instancetype)mdTextIconWithSize:(CGFloat)size;
+ (instancetype)mdThermometerIconWithSize:(CGFloat)size;
+ (instancetype)mdThumbsDownIconWithSize:(CGFloat)size;
+ (instancetype)mdThumbsUpIconWithSize:(CGFloat)size;
+ (instancetype)mdThunderstormIconWithSize:(CGFloat)size;
+ (instancetype)mdTimeIconWithSize:(CGFloat)size;
+ (instancetype)mdTimerIconWithSize:(CGFloat)size;
+ (instancetype)mdTodayIconWithSize:(CGFloat)size;
+ (instancetype)mdTrainIconWithSize:(CGFloat)size;
+ (instancetype)mdTransgenderIconWithSize:(CGFloat)size;
+ (instancetype)mdTrashIconWithSize:(CGFloat)size;
+ (instancetype)mdTrendingDownIconWithSize:(CGFloat)size;
+ (instancetype)mdTrendingUpIconWithSize:(CGFloat)size;
+ (instancetype)mdTrophyIconWithSize:(CGFloat)size;
+ (instancetype)mdTvIconWithSize:(CGFloat)size;
+ (instancetype)mdUmbrellaIconWithSize:(CGFloat)size;
+ (instancetype)mdUndoIconWithSize:(CGFloat)size;
+ (instancetype)mdUnlockIconWithSize:(CGFloat)size;
+ (instancetype)mdVideocamIconWithSize:(CGFloat)size;
+ (instancetype)mdVolumeHighIconWithSize:(CGFloat)size;
+ (instancetype)mdVolumeLowIconWithSize:(CGFloat)size;
+ (instancetype)mdVolumeMuteIconWithSize:(CGFloat)size;
+ (instancetype)mdVolumeOffIconWithSize:(CGFloat)size;
+ (instancetype)mdWalkIconWithSize:(CGFloat)size;
+ (instancetype)mdWalletIconWithSize:(CGFloat)size;
+ (instancetype)mdWarningIconWithSize:(CGFloat)size;
+ (instancetype)mdWatchIconWithSize:(CGFloat)size;
+ (instancetype)mdWaterIconWithSize:(CGFloat)size;
+ (instancetype)mdWifiIconWithSize:(CGFloat)size;
+ (instancetype)mdWineIconWithSize:(CGFloat)size;
+ (instancetype)mdWomanIconWithSize:(CGFloat)size;

@end

@interface FAKIonIcons (Unavailable)

+ (instancetype)ios7AlarmIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosAlarmIconWithSize: instead")));
+ (instancetype)ios7AlarmOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosAlarmOutlineIconWithSize: instead")));
+ (instancetype)ios7AlbumsIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosAlbumsIconWithSize: instead")));
+ (instancetype)ios7AlbumsOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosAlbumsOutlineIconWithSize: instead")));
+ (instancetype)ios7AmericanfootballIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosAmericanfootballIconWithSize: instead")));
+ (instancetype)ios7AmericanfootballOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosAmericanfootballOutlineIconWithSize: instead")));
+ (instancetype)ios7AnalyticsIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosAnalyticsIconWithSize: instead")));
+ (instancetype)ios7AnalyticsOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosAnalyticsOutlineIconWithSize: instead")));
+ (instancetype)ios7ArrowBackIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosArrowBackIconWithSize: instead")));
+ (instancetype)ios7ArrowDownIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosArrowDownIconWithSize: instead")));
+ (instancetype)ios7ArrowForwardIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosArrowForwardIconWithSize: instead")));
+ (instancetype)ios7ArrowLeftIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosArrowLeftIconWithSize: instead")));
+ (instancetype)ios7ArrowRightIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosArrowRightIconWithSize: instead")));
+ (instancetype)ios7ArrowThinDownIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosArrowThinDownIconWithSize: instead")));
+ (instancetype)ios7ArrowThinLeftIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosArrowThinLeftIconWithSize: instead")));
+ (instancetype)ios7ArrowThinRightIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosArrowThinRightIconWithSize: instead")));
+ (instancetype)ios7ArrowThinUpIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosArrowThinUpIconWithSize: instead")));
+ (instancetype)ios7ArrowUpIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosArrowUpIconWithSize: instead")));
+ (instancetype)ios7AtIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosAtIconWithSize: instead")));
+ (instancetype)ios7AtOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosAtOutlineIconWithSize: instead")));
+ (instancetype)ios7BarcodeIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBarcodeIconWithSize: instead")));
+ (instancetype)ios7BarcodeOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBarcodeOutlineIconWithSize: instead")));
+ (instancetype)ios7BaseballIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBaseballIconWithSize: instead")));
+ (instancetype)ios7BaseballOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBaseballOutlineIconWithSize: instead")));
+ (instancetype)ios7BasketballIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBasketballIconWithSize: instead")));
+ (instancetype)ios7BasketballOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBasketballOutlineIconWithSize: instead")));
+ (instancetype)ios7BellIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBellIconWithSize: instead")));
+ (instancetype)ios7BellOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBellOutlineIconWithSize: instead")));
+ (instancetype)ios7BoltIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBoltIconWithSize: instead")));
+ (instancetype)ios7BoltOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBoltOutlineIconWithSize: instead")));
+ (instancetype)ios7BookmarksIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBookmarksIconWithSize: instead")));
+ (instancetype)ios7BookmarksOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBookmarksOutlineIconWithSize: instead")));
+ (instancetype)ios7BoxIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBoxIconWithSize: instead")));
+ (instancetype)ios7BoxOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBoxOutlineIconWithSize: instead")));
+ (instancetype)ios7BriefcaseIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBriefcaseIconWithSize: instead")));
+ (instancetype)ios7BriefcaseOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBriefcaseOutlineIconWithSize: instead")));
+ (instancetype)ios7BrowsersIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBrowsersIconWithSize: instead")));
+ (instancetype)ios7BrowsersOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBrowsersOutlineIconWithSize: instead")));
+ (instancetype)ios7CalculatorIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCalculatorIconWithSize: instead")));
+ (instancetype)ios7CalculatorOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCalculatorOutlineIconWithSize: instead")));
+ (instancetype)ios7CalendarIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCalendarIconWithSize: instead")));
+ (instancetype)ios7CalendarOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCalendarOutlineIconWithSize: instead")));
+ (instancetype)ios7CameraIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCameraIconWithSize: instead")));
+ (instancetype)ios7CameraOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCameraOutlineIconWithSize: instead")));
+ (instancetype)ios7CartIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCartIconWithSize: instead")));
+ (instancetype)ios7CartOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCartOutlineIconWithSize: instead")));
+ (instancetype)ios7ChatboxesIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosChatboxesIconWithSize: instead")));
+ (instancetype)ios7ChatboxesOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosChatboxesOutlineIconWithSize: instead")));
+ (instancetype)ios7ChatbubbleIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosChatbubbleIconWithSize: instead")));
+ (instancetype)ios7ChatbubbleOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosChatbubbleOutlineIconWithSize: instead")));
+ (instancetype)ios7CheckmarkIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCheckmarkIconWithSize: instead")));
+ (instancetype)ios7CheckmarkEmptyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCheckmarkEmptyIconWithSize: instead")));
+ (instancetype)ios7CheckmarkOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCheckmarkOutlineIconWithSize: instead")));
+ (instancetype)ios7CircleFilledIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCircleFilledIconWithSize: instead")));
+ (instancetype)ios7CircleOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCircleOutlineIconWithSize: instead")));
+ (instancetype)ios7ClockIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosClockIconWithSize: instead")));
+ (instancetype)ios7ClockOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosClockOutlineIconWithSize: instead")));
+ (instancetype)ios7CloseIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloseIconWithSize: instead")));
+ (instancetype)ios7CloseEmptyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloseEmptyIconWithSize: instead")));
+ (instancetype)ios7CloseOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloseOutlineIconWithSize: instead")));
+ (instancetype)ios7CloudIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloudIconWithSize: instead")));
+ (instancetype)ios7CloudDownloadIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloudDownloadIconWithSize: instead")));
+ (instancetype)ios7CloudDownloadOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloudDownloadOutlineIconWithSize: instead")));
+ (instancetype)ios7CloudOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloudOutlineIconWithSize: instead")));
+ (instancetype)ios7CloudUploadIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloudUploadIconWithSize: instead")));
+ (instancetype)ios7CloudUploadOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloudUploadOutlineIconWithSize: instead")));
+ (instancetype)ios7CloudyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloudyIconWithSize: instead")));
+ (instancetype)ios7CloudyNightIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloudyNightIconWithSize: instead")));
+ (instancetype)ios7CloudyNightOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloudyNightOutlineIconWithSize: instead")));
+ (instancetype)ios7CloudyOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloudyOutlineIconWithSize: instead")));
+ (instancetype)ios7CogIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCogIconWithSize: instead")));
+ (instancetype)ios7CogOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCogOutlineIconWithSize: instead")));
+ (instancetype)ios7ComposeIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosComposeIconWithSize: instead")));
+ (instancetype)ios7ComposeOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosComposeOutlineIconWithSize: instead")));
+ (instancetype)ios7ContactIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosContactIconWithSize: instead")));
+ (instancetype)ios7ContactOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosContactOutlineIconWithSize: instead")));
+ (instancetype)ios7CopyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCopyIconWithSize: instead")));
+ (instancetype)ios7CopyOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCopyOutlineIconWithSize: instead")));
+ (instancetype)ios7DownloadIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosDownloadIconWithSize: instead")));
+ (instancetype)ios7DownloadOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosDownloadOutlineIconWithSize: instead")));
+ (instancetype)ios7DragIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosDragIconWithSize: instead")));
+ (instancetype)ios7EmailIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosEmailIconWithSize: instead")));
+ (instancetype)ios7EmailOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosEmailOutlineIconWithSize: instead")));
+ (instancetype)ios7ExpandIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosExpandIconWithSize: instead")));
+ (instancetype)ios7EyeIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosEyeIconWithSize: instead")));
+ (instancetype)ios7EyeOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosEyeOutlineIconWithSize: instead")));
+ (instancetype)ios7FastforwardIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFastforwardIconWithSize: instead")));
+ (instancetype)ios7FastforwardOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFastforwardOutlineIconWithSize: instead")));
+ (instancetype)ios7FilingIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFilingIconWithSize: instead")));
+ (instancetype)ios7FilingOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFilingOutlineIconWithSize: instead")));
+ (instancetype)ios7FilmIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFilmIconWithSize: instead")));
+ (instancetype)ios7FilmOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFilmOutlineIconWithSize: instead")));
+ (instancetype)ios7FlagIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFlagIconWithSize: instead")));
+ (instancetype)ios7FlagOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFlagOutlineIconWithSize: instead")));
+ (instancetype)ios7FolderIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFolderIconWithSize: instead")));
+ (instancetype)ios7FolderOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFolderOutlineIconWithSize: instead")));
+ (instancetype)ios7FootballIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFootballIconWithSize: instead")));
+ (instancetype)ios7FootballOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFootballOutlineIconWithSize: instead")));
+ (instancetype)ios7GearIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosGearIconWithSize: instead")));
+ (instancetype)ios7GearOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosGearOutlineIconWithSize: instead")));
+ (instancetype)ios7GlassesIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosGlassesIconWithSize: instead")));
+ (instancetype)ios7GlassesOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosGlassesOutlineIconWithSize: instead")));
+ (instancetype)ios7HeartIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosHeartIconWithSize: instead")));
+ (instancetype)ios7HeartOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosHeartOutlineIconWithSize: instead")));
+ (instancetype)ios7HelpIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosHelpIconWithSize: instead")));
+ (instancetype)ios7HelpEmptyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosHelpEmptyIconWithSize: instead")));
+ (instancetype)ios7HelpOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosHelpOutlineIconWithSize: instead")));
+ (instancetype)ios7HomeIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosHomeIconWithSize: instead")));
+ (instancetype)ios7HomeOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosHomeOutlineIconWithSize: instead")));
+ (instancetype)ios7InfiniteIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosInfiniteIconWithSize: instead")));
+ (instancetype)ios7InfiniteOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosInfiniteOutlineIconWithSize: instead")));
+ (instancetype)ios7InformationIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosInformationIconWithSize: instead")));
+ (instancetype)ios7InformationEmptyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosInformationEmptyIconWithSize: instead")));
+ (instancetype)ios7InformationOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosInformationOutlineIconWithSize: instead")));
+ (instancetype)ios7IonicOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosIonicOutlineIconWithSize: instead")));
+ (instancetype)ios7KeypadIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosKeypadIconWithSize: instead")));
+ (instancetype)ios7KeypadOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosKeypadOutlineIconWithSize: instead")));
+ (instancetype)ios7LightbulbIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosLightbulbIconWithSize: instead")));
+ (instancetype)ios7LightbulbOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosLightbulbOutlineIconWithSize: instead")));
+ (instancetype)ios7LocationIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosLocationIconWithSize: instead")));
+ (instancetype)ios7LocationOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosLocationOutlineIconWithSize: instead")));
+ (instancetype)ios7LockedIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosLockedIconWithSize: instead")));
+ (instancetype)ios7LockedOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosLockedOutlineIconWithSize: instead")));
+ (instancetype)ios7LoopIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosLoopIconWithSize: instead")));
+ (instancetype)ios7LoopStrongIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosLoopStrongIconWithSize: instead")));
+ (instancetype)ios7MedkitIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMedkitIconWithSize: instead")));
+ (instancetype)ios7MedkitOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMedkitOutlineIconWithSize: instead")));
+ (instancetype)ios7MicIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMicIconWithSize: instead")));
+ (instancetype)ios7MicOffIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMicOffIconWithSize: instead")));
+ (instancetype)ios7MicOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMicOutlineIconWithSize: instead")));
+ (instancetype)ios7MinusIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMinusIconWithSize: instead")));
+ (instancetype)ios7MinusEmptyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMinusEmptyIconWithSize: instead")));
+ (instancetype)ios7MinusOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMinusOutlineIconWithSize: instead")));
+ (instancetype)ios7MonitorIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMonitorIconWithSize: instead")));
+ (instancetype)ios7MonitorOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMonitorOutlineIconWithSize: instead")));
+ (instancetype)ios7MoonIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMoonIconWithSize: instead")));
+ (instancetype)ios7MoonOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMoonOutlineIconWithSize: instead")));
+ (instancetype)ios7MoreIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMoreIconWithSize: instead")));
+ (instancetype)ios7MoreOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMoreOutlineIconWithSize: instead")));
+ (instancetype)ios7MusicalNoteIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMusicalNoteIconWithSize: instead")));
+ (instancetype)ios7MusicalNotesIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMusicalNotesIconWithSize: instead")));
+ (instancetype)ios7NavigateIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosNavigateIconWithSize: instead")));
+ (instancetype)ios7NavigateOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosNavigateOutlineIconWithSize: instead")));
+ (instancetype)ios7PaperIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPaperIconWithSize: instead")));
+ (instancetype)ios7PaperOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPaperOutlineIconWithSize: instead")));
+ (instancetype)ios7PaperplaneIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPaperplaneIconWithSize: instead")));
+ (instancetype)ios7PaperplaneOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPaperplaneOutlineIconWithSize: instead")));
+ (instancetype)ios7PartlysunnyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPartlysunnyIconWithSize: instead")));
+ (instancetype)ios7PartlysunnyOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPartlysunnyOutlineIconWithSize: instead")));
+ (instancetype)ios7PauseIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPauseIconWithSize: instead")));
+ (instancetype)ios7PauseOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPauseOutlineIconWithSize: instead")));
+ (instancetype)ios7PawIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPawIconWithSize: instead")));
+ (instancetype)ios7PawOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPawOutlineIconWithSize: instead")));
+ (instancetype)ios7PeopleIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPeopleIconWithSize: instead")));
+ (instancetype)ios7PeopleOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPeopleOutlineIconWithSize: instead")));
+ (instancetype)ios7PersonIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPersonIconWithSize: instead")));
+ (instancetype)ios7PersonOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPersonOutlineIconWithSize: instead")));
+ (instancetype)ios7PersonaddIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPersonaddIconWithSize: instead")));
+ (instancetype)ios7PersonaddOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPersonaddOutlineIconWithSize: instead")));
+ (instancetype)ios7PhotosIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPhotosIconWithSize: instead")));
+ (instancetype)ios7PhotosOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPhotosOutlineIconWithSize: instead")));
+ (instancetype)ios7PieIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPieIconWithSize: instead")));
+ (instancetype)ios7PieOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPieOutlineIconWithSize: instead")));
+ (instancetype)ios7PlayIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPlayIconWithSize: instead")));
+ (instancetype)ios7PlayOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPlayOutlineIconWithSize: instead")));
+ (instancetype)ios7PlusIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPlusIconWithSize: instead")));
+ (instancetype)ios7PlusEmptyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPlusEmptyIconWithSize: instead")));
+ (instancetype)ios7PlusOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPlusOutlineIconWithSize: instead")));
+ (instancetype)ios7PricetagIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPricetagIconWithSize: instead")));
+ (instancetype)ios7PricetagOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPricetagOutlineIconWithSize: instead")));
+ (instancetype)ios7PricetagsIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPricetagsIconWithSize: instead")));
+ (instancetype)ios7PricetagsOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPricetagsOutlineIconWithSize: instead")));
+ (instancetype)ios7PrinterIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPrinterIconWithSize: instead")));
+ (instancetype)ios7PrinterOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPrinterOutlineIconWithSize: instead")));
+ (instancetype)ios7PulseIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPulseIconWithSize: instead")));
+ (instancetype)ios7PulseStrongIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPulseStrongIconWithSize: instead")));
+ (instancetype)ios7RainyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosRainyIconWithSize: instead")));
+ (instancetype)ios7RainyOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosRainyOutlineIconWithSize: instead")));
+ (instancetype)ios7RecordingIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosRecordingIconWithSize: instead")));
+ (instancetype)ios7RecordingOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosRecordingOutlineIconWithSize: instead")));
+ (instancetype)ios7RedoIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosRedoIconWithSize: instead")));
+ (instancetype)ios7RedoOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosRedoOutlineIconWithSize: instead")));
+ (instancetype)ios7RefreshIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosRefreshIconWithSize: instead")));
+ (instancetype)ios7RefreshEmptyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosRefreshEmptyIconWithSize: instead")));
+ (instancetype)ios7RefreshOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosRefreshOutlineIconWithSize: instead")));
+ (instancetype)ios7ReloadbeforeionIos7ReloadingIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosReloadbeforeionIos7ReloadingIconWithSize: instead")));
+ (instancetype)ios7ReverseCameraIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosReverseCameraIconWithSize: instead")));
+ (instancetype)ios7ReverseCameraOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosReverseCameraOutlineIconWithSize: instead")));
+ (instancetype)ios7RewindIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosRewindIconWithSize: instead")));
+ (instancetype)ios7RewindOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosRewindOutlineIconWithSize: instead")));
+ (instancetype)ios7SearchIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSearchIconWithSize: instead")));
+ (instancetype)ios7SearchStrongIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSearchStrongIconWithSize: instead")));
+ (instancetype)ios7SettingsIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSettingsIconWithSize: instead")));
+ (instancetype)ios7SettingsStrongIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSettingsStrongIconWithSize: instead")));
+ (instancetype)ios7ShrinkIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosShrinkIconWithSize: instead")));
+ (instancetype)ios7SkipbackwardIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSkipbackwardIconWithSize: instead")));
+ (instancetype)ios7SkipbackwardOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSkipbackwardOutlineIconWithSize: instead")));
+ (instancetype)ios7SkipforwardIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSkipforwardIconWithSize: instead")));
+ (instancetype)ios7SkipforwardOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSkipforwardOutlineIconWithSize: instead")));
+ (instancetype)ios7SnowyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSnowyIconWithSize: instead")));
+ (instancetype)ios7SpeedometerIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSpeedometerIconWithSize: instead")));
+ (instancetype)ios7SpeedometerOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSpeedometerOutlineIconWithSize: instead")));
+ (instancetype)ios7StarIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosStarIconWithSize: instead")));
+ (instancetype)ios7StarHalfIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosStarHalfIconWithSize: instead")));
+ (instancetype)ios7StarOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosStarOutlineIconWithSize: instead")));
+ (instancetype)ios7StopwatchIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosStopwatchIconWithSize: instead")));
+ (instancetype)ios7StopwatchOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosStopwatchOutlineIconWithSize: instead")));
+ (instancetype)ios7SunnyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSunnyIconWithSize: instead")));
+ (instancetype)ios7SunnyOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSunnyOutlineIconWithSize: instead")));
+ (instancetype)ios7TelephoneIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosTelephoneIconWithSize: instead")));
+ (instancetype)ios7TelephoneOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosTelephoneOutlineIconWithSize: instead")));
+ (instancetype)ios7TennisballIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosTennisballIconWithSize: instead")));
+ (instancetype)ios7TennisballOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosTennisballOutlineIconWithSize: instead")));
+ (instancetype)ios7ThunderstormIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosThunderstormIconWithSize: instead")));
+ (instancetype)ios7ThunderstormOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosThunderstormOutlineIconWithSize: instead")));
+ (instancetype)ios7TimeIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosTimeIconWithSize: instead")));
+ (instancetype)ios7TimeOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosTimeOutlineIconWithSize: instead")));
+ (instancetype)ios7TimerIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosTimerIconWithSize: instead")));
+ (instancetype)ios7TimerOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosTimerOutlineIconWithSize: instead")));
+ (instancetype)ios7ToggleIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosToggleIconWithSize: instead")));
+ (instancetype)ios7ToggleOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosToggleOutlineIconWithSize: instead")));
+ (instancetype)ios7TrashIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosTrashIconWithSize: instead")));
+ (instancetype)ios7TrashOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosTrashOutlineIconWithSize: instead")));
+ (instancetype)ios7UndoIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosUndoIconWithSize: instead")));
+ (instancetype)ios7UndoOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosUndoOutlineIconWithSize: instead")));
+ (instancetype)ios7UnlockedIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosUnlockedIconWithSize: instead")));
+ (instancetype)ios7UnlockedOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosUnlockedOutlineIconWithSize: instead")));
+ (instancetype)ios7UploadIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosUploadIconWithSize: instead")));
+ (instancetype)ios7UploadOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosUploadOutlineIconWithSize: instead")));
+ (instancetype)ios7VideocamIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosVideocamIconWithSize: instead")));
+ (instancetype)ios7VideocamOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosVideocamOutlineIconWithSize: instead")));
+ (instancetype)ios7VolumeHighIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosVolumeHighIconWithSize: instead")));
+ (instancetype)ios7VolumeLowIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosVolumeLowIconWithSize: instead")));
+ (instancetype)ios7WineglassIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosWineglassIconWithSize: instead")));
+ (instancetype)ios7WineglassOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosWineglassOutlineIconWithSize: instead")));
+ (instancetype)ios7WorldIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosWorldIconWithSize: instead")));
+ (instancetype)ios7WorldOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosWorldOutlineIconWithSize: instead")));

@end
